#!/usr/bin/env bash

#jackd -R -P 10 -t 0 -v -d alsa -z n -D -H -n 2 -p 1024 -r 44100
#jackd -R -P 10 -t 0 -v -c s -d alsa #-z n -D -H -n 2 -p 1024 -r 44100
#jackd -R -P 10 -t 0 -v -c s -d alsa -z n -D -H -n 2 -p 1024 -r 44100
#jackd -R -P 10 -t 0 -v -c s -d alsa -d hw:D10,0 -z n -D -H -n 3 -p 1024 -r 44100

#jackd -n cmus -R -P 10 -t 0 -v -c s -d alsa -d hw:D10,0 -z n -D -H -n 3 -p 1024 -r 44100


#/usr/bin/jackd -Rv -P10 -dalsa -D -p4096 -Phw:D10 -r44100  #esto anda
#nohup /usr/bin/jackd -Rv -P10 -t0 -cs -dalsa -D -p4096 -Phw:D10 -r44100 > /dev/null 2>&1&
nohup /usr/bin/jackd -R -P10 -t0 -Tuv -cs -dalsa -D -p1024 -Phw:D10 -r44100 > /dev/null 2>&1&
#nohup /usr/bin/jackd -R -P10 -t0 -Tuv -cs -dalsa -D -p1024 -Phw:D10 -r48000 > /dev/null 2>&1&


# 20240426
# conexion actual
#/usr/bin/jackd -v -S -dalsa -dhw:D10 -r48000 -p4096 -D -Phw:D10
