#!/usr/bin/env bash

set -o nounset
set -o errexit

poolindex="$1"
dsindex="$2"

pool=("booklib" "data_01" "msk_01" "dirt1991")
ds=("kof" "passwdvault" "layne88")

case ${dsindex} in
	0)
		zfs load-key -r "${pool[$poolindex]}/${ds[$dsindex]}"
		for i in /mnt/datad_01/${ds[$dsindex]}/*; do
			dirname="$(printf '%s\n' $i | sed 's/^[^:]*[/]//')"
			zfs mount -v "${pool[$poolindex]}/${ds[$dsindex]}/${dirname}"
		done
		;;
	1)
		zfs load-key -r "${pool[$poolindex]}/${ds[$dsindex]}"
		zfs mount -v "${pool[$poolindex]}/${ds[$dsindex]}"
		;;
	2)
		zfs load-key -r "${pool[$poolindex]}/${ds[$dsindex]}"
		zfs mount -v "${pool[$poolindex]}/${ds[$dsindex]}"
		;;
esac
