#!/usr/bin/env bash

argsarray=("$@")

serverstatus="$(rc-service mysql status | cut -d ":" -f 2 | sed 's/ //')"

if [[ "${serverstatus}" == "stopped" ]]; then
	printf '%s\n' "mysql is stopped, run 'dbs 0' to start it"
else
	mysql -u "${argsarray[0]}" -p"${argsarray[1]}" -h 127.0.0.1
fi
