#!/usr/bin/env bash

date_ns=$(date --iso-8601=ns | sed -e 's/://g;s/-/_/3g;s/-//g;s/T/t/g;s/,/_/g')

dmesg --time-format iso > "/users/juancho_gentoo/linuxstp/install/linux_kernel/dmesg_d/dmesg_extracts/dmesg_extract_${date_ns}"
chown juancho:juancho "/users/juancho_gentoo/linuxstp/install/linux_kernel/dmesg_d/dmesg_extracts/dmesg_extract_${date_ns}"
