#!/usr/bin/env bash

set -o nounset
set -o errexit

# version 1.3

argsarray=("$@")
impexpindex="${argsarray[0]}"
poolindex="${argsarray[1]}"

impexp=("import" "export")
pool=("booklib" "data_01" "msk01" "dirt1991")

zpool ${impexp["${impexpindex}"]} ${pool["${poolindex}"]}
